name: dotnet package
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies of API project
        run: dotnet restore ${{ github.workspace }}/MoviesApi/WebAPI/WebAPI.csproj
      - name: Build
        run: dotnet build ${{ github.workspace }}/MoviesApi/WebAPI/WebAPI.csproj --no-restore
      - name: Test
        run: dotnet test ${{ github.workspace }}/MoviesApi/Application.UnitTests/Application.UnitTests.csproj --no-build --verbosity normal
